name: Build and test

on: [push, pull_request]

jobs:
  package:
    name: Maven Build and Test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'
      - name: Build with Maven
        run: mvn --batch-mode -show-version --update-snapshots --errors package
      - name: Publish Unit Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always() # also run if build step failed
        with:
          junit_files: target/surefire-reports/*.xml
